repos:
  # Backend
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy

  # Frontend
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.20.1
    hooks:
      - id: eslint
        name: eslint (React/Vite)
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        args: ["--config", "frontend/tasks-app/eslint.config.js"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier (React/Vite)
        files: \.(js|jsx|ts|tsx|json|css|md|yaml|yml)$
        types: [file]
